# Production Dockerfile for Cruzible (Explorer, Staking, Governance)
# Requires next.config.js to have: output: 'standalone'

# Stage 1: Dependencies
FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --no-fund --ignore-scripts
# Rebuild only the audited native runtime package required by Next.js images.
RUN npm rebuild sharp --no-fund

# Stage 2: Build
FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_CHAIN_ENV
ARG NEXT_PUBLIC_AETHELRED_MAINNET_CHAIN_ID
ARG NEXT_PUBLIC_AETHELRED_MAINNET_RPC_URL
ARG NEXT_PUBLIC_AETHELRED_MAINNET_EXPLORER_URL
ARG NEXT_PUBLIC_AETHELRED_TESTNET_RPC_URL
ARG NEXT_PUBLIC_AETHELRED_TESTNET_EXPLORER_URL
ARG NEXT_PUBLIC_AETHELRED_DEVNET_RPC_URL
ARG NEXT_PUBLIC_AETHELRED_GENESIS_HASH
ARG NEXT_PUBLIC_CRUZIBLE_ADDRESS
ARG NEXT_PUBLIC_STAETHEL_ADDRESS
ARG NEXT_PUBLIC_AETHEL_TOKEN_ADDRESS
ARG NEXT_PUBLIC_GOVERNANCE_ADDRESS
ARG NEXT_PUBLIC_STABLECOIN_BRIDGE_ADDRESS
ARG NEXT_PUBLIC_USDC_TOKEN_ADDRESS
ARG NEXT_PUBLIC_USDT_TOKEN_ADDRESS
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_ZEROID_APP_URL
ARG NEXT_PUBLIC_APP_VERSION
ARG CRUZIBLE_EXTRA_API_ORIGINS
ARG CRUZIBLE_ALLOW_PLAINTEXT_HTTP
# NEXT_PUBLIC_* values are compiled into browser bundles during next build.
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_CHAIN_ENV=${NEXT_PUBLIC_CHAIN_ENV}
ENV NEXT_PUBLIC_AETHELRED_MAINNET_CHAIN_ID=${NEXT_PUBLIC_AETHELRED_MAINNET_CHAIN_ID}
ENV NEXT_PUBLIC_AETHELRED_MAINNET_RPC_URL=${NEXT_PUBLIC_AETHELRED_MAINNET_RPC_URL}
ENV NEXT_PUBLIC_AETHELRED_MAINNET_EXPLORER_URL=${NEXT_PUBLIC_AETHELRED_MAINNET_EXPLORER_URL}
ENV NEXT_PUBLIC_AETHELRED_TESTNET_RPC_URL=${NEXT_PUBLIC_AETHELRED_TESTNET_RPC_URL}
ENV NEXT_PUBLIC_AETHELRED_TESTNET_EXPLORER_URL=${NEXT_PUBLIC_AETHELRED_TESTNET_EXPLORER_URL}
ENV NEXT_PUBLIC_AETHELRED_DEVNET_RPC_URL=${NEXT_PUBLIC_AETHELRED_DEVNET_RPC_URL}
ENV NEXT_PUBLIC_AETHELRED_GENESIS_HASH=${NEXT_PUBLIC_AETHELRED_GENESIS_HASH}
ENV NEXT_PUBLIC_CRUZIBLE_ADDRESS=${NEXT_PUBLIC_CRUZIBLE_ADDRESS}
ENV NEXT_PUBLIC_STAETHEL_ADDRESS=${NEXT_PUBLIC_STAETHEL_ADDRESS}
ENV NEXT_PUBLIC_AETHEL_TOKEN_ADDRESS=${NEXT_PUBLIC_AETHEL_TOKEN_ADDRESS}
ENV NEXT_PUBLIC_GOVERNANCE_ADDRESS=${NEXT_PUBLIC_GOVERNANCE_ADDRESS}
ENV NEXT_PUBLIC_STABLECOIN_BRIDGE_ADDRESS=${NEXT_PUBLIC_STABLECOIN_BRIDGE_ADDRESS}
ENV NEXT_PUBLIC_USDC_TOKEN_ADDRESS=${NEXT_PUBLIC_USDC_TOKEN_ADDRESS}
ENV NEXT_PUBLIC_USDT_TOKEN_ADDRESS=${NEXT_PUBLIC_USDT_TOKEN_ADDRESS}
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
ENV NEXT_PUBLIC_ZEROID_APP_URL=${NEXT_PUBLIC_ZEROID_APP_URL}
ENV NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION}
ENV CRUZIBLE_EXTRA_API_ORIGINS=${CRUZIBLE_EXTRA_API_ORIGINS}
ENV CRUZIBLE_ALLOW_PLAINTEXT_HTTP=${CRUZIBLE_ALLOW_PLAINTEXT_HTTP}
RUN test -n "$NEXT_PUBLIC_API_URL" || (echo "NEXT_PUBLIC_API_URL build arg is required" && exit 1); \
    test -n "$NEXT_PUBLIC_CHAIN_ENV" || (echo "NEXT_PUBLIC_CHAIN_ENV build arg is required" && exit 1); \
    test -n "$NEXT_PUBLIC_AETHELRED_GENESIS_HASH" || (echo "NEXT_PUBLIC_AETHELRED_GENESIS_HASH build arg is required" && exit 1); \
    case "$NEXT_PUBLIC_CHAIN_ENV" in \
      testnet) test -n "$NEXT_PUBLIC_AETHELRED_TESTNET_RPC_URL" || (echo "NEXT_PUBLIC_AETHELRED_TESTNET_RPC_URL build arg is required for testnet" && exit 1) ;; \
      mainnet) \
        test -n "$NEXT_PUBLIC_AETHELRED_MAINNET_CHAIN_ID" || (echo "NEXT_PUBLIC_AETHELRED_MAINNET_CHAIN_ID build arg is required for mainnet" && exit 1); \
        test -n "$NEXT_PUBLIC_AETHELRED_MAINNET_RPC_URL" || (echo "NEXT_PUBLIC_AETHELRED_MAINNET_RPC_URL build arg is required for mainnet" && exit 1); \
        test -n "$NEXT_PUBLIC_AETHELRED_MAINNET_EXPLORER_URL" || (echo "NEXT_PUBLIC_AETHELRED_MAINNET_EXPLORER_URL build arg is required for mainnet" && exit 1) ;; \
      devnet) ;; \
      *) echo "NEXT_PUBLIC_CHAIN_ENV must be mainnet, testnet, or devnet"; exit 1 ;; \
    esac; \
    npm run build

# Stage 3: Production
FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Server-side middleware evaluates these at runtime. Operators may override
# them with `docker run -e` or orchestrator env without rebuilding the image.
ENV CRUZIBLE_EXTRA_API_ORIGINS=""
ENV CRUZIBLE_ALLOW_PLAINTEXT_HTTP="false"
RUN apk add --no-cache dumb-init
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/api/health').then((response) => process.exit(response.ok ? 0 : 1)).catch(() => process.exit(1))"
ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "server.js"]
